title: Dokkodo
description: Money · Meditations · Music · Mountains
url: "https://dokkodo.xyz"
baseurl: ""

collections:
  money:
    output: true
    permalink: /money/:title/
  meditations:
    output: true
    permalink: /meditations/:title/
  music:
    output: true
    permalink: /music/:title/
  mountains:
    output: true
    permalink: /mountains/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag

markdown: kramdown
